version: '3.9'

services:
  notesapp:
    build: .
    container_name: notesapp
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
